// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateCourse(ctx context.Context, arg CreateCourseParams) (Course, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteCourse(ctx context.Context, id uuid.UUID) error
	GetAllCourse(ctx context.Context) ([]Course, error)
	GetCourseById(ctx context.Context, id uuid.UUID) (Course, error)
	GetUser(ctx context.Context, email string) (User, error)
	UpdateCourse(ctx context.Context, arg UpdateCourseParams) (Course, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	VerifyUser(ctx context.Context, arg VerifyUserParams) (User, error)
	getAllUsers(ctx context.Context) ([]User, error)
}

var _ Querier = (*Queries)(nil)
